name: Appeal
description: Request removal from blocklist
title: "[APPEAL] "
labels: ["appeal"]
body:
  - type: textarea
    id: domains
    attributes:
      label: Blocked domains or IPs
      description: One per line
      placeholder: |
        https://my-site.com
        my-domain.org
    validations:
      required: true
  
  - type: textarea
    id: reason
    attributes:
      label: Why should this be unblocked?
      description: Explain legitimacy
      placeholder: This is my website / False positive because...
    validations:
      required: true
  
  - type: input
    id: contact
    attributes:
      label: Contact email (optional)
      placeholder: admin@domain.com
    validations:
      required: false
  
  - type: checkboxes
    id: duplicate
    attributes:
      label: Duplicate check
      options:
        - label: This is not a duplicate request
          required: true