name: Check Links
on:
  schedule:
    - cron: "0 12 1 * *"
  workflow_dispatch:

jobs:
  links:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          config-file: ".github/mlc_config.json"
